import { SEO } from '../components/SEO';

export function Legal() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12 flex-1 w-full">
      <SEO 
        title="Legal & Disclaimer | Feed by Rural Utility Cost" 
        description="Legal terms and disclaimers for the Feed app by Rural Utility Cost." 
      />
      <h1 className="text-3xl font-bold text-slate-text mb-6 tracking-tight">Legal & Disclaimer</h1>
      
      <div className="bg-white border border-slate-200 rounded-xl p-8 text-sm leading-relaxed text-slate-sub space-y-6">
        <div className="bg-amber-50 border-l-[3px] border-amber-500 p-4 rounded-r-md text-amber-900 font-medium">
          Important Notice: The calculations and results provided by the Feed app and the Rural Utility Cost network are estimates intended for decision support and planning purposes only.
        </div>
        
        <h2 className="text-xl font-bold text-slate-text mt-8 mb-3">Decision Support</h2>
        <p>
          The tools, calculators, and information provided here are not intended to replace professional agricultural, financial, or nutritional advice. Variables in weather, animal genetics, regional pricing, and localized feeding practices can heavily alter actual outcomes.
        </p>
        <p>
          Users should verify all estimates and important business decisions independently, and consult with a certified livestock nutritionist or financial advisor prior to making significant investments or changes to their feeding programs.
        </p>

        <h2 className="text-xl font-bold text-slate-text mt-8 mb-3">Warranties</h2>
        <p>
          Rural Utility Cost makes no guarantees regarding the exactness, robustness, or reliability of the data outcomes generated by these calculators. Information is used at your own risk.
        </p>

        <h2 className="text-xl font-bold text-slate-text mt-8 mb-3">Shared Ecosystem</h2>
        <p>
          This Legal page is governed by the master terms of service set out by Rural Utility Cost. Refer to the primary site for full Terms of Use and Privacy Policy guidelines.
        </p>
      </div>
    </div>
  );
}
